version: '3'
services:
  db_mysql:
    image: mysql:8.0
    container_name: shop_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eshop
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: shop_redis
    ports:
      - "6379:6379"
  #  db_postgres:
  #    image: postgres:15
  #    container_name: shop_postgres_db
  #    restart: always
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: 123456
  #      POSTGRES_DB: eshop